### PR TITLE
Added missing dependency

### PR DESCRIPTION
**Pull request by elazer**

### CODE REVIEW

**Comment by teohhanhui** [comment]
Omg Tripviss is still alive?! :rofl:

**Comment by leesiongchan** [comment]
Nope, we still use it for other projects, should have fork it instead of polluting but I am too lazy to setup.

**Comment by teohhanhui** [comment]
I think it's pretty outdated lol... You should check out our latest Docker setup in API Platform.

**Comment by leesiongchan** [comment]
Yeah we are using apiplatform docker for deployment but this for ci/cd. Want to update the script but not free yet haha.

**Pull request merged**
